#!/usr/bin/env python3
"""
fetch_ccil.py
--------------
Downloads today's CCIL Daily Market Analytics PDF with NO login (confirmed - the
report is genuinely public, tested in an incognito browser).

Two separate findings from testing this by hand, which is why the script is split
into two different HTTP mechanisms:

1. DISCOVERING today's exact URL needs a real rendered page. The download link is
   generated by client-side JS as an onclick="guestUserCheck('...pdf...')" attribute
   that is populated by a JS/AJAX call AFTER initial page load - a plain GET of the
   page's HTML does not contain it (confirmed - a direct fetch of the page returned
   only the generic "please select files" placeholder, not the real per-day button).
   So this step uses a headless browser (Playwright) just to render the page and
   read the resulting DOM.

2. DOWNLOADING the actual PDF, once you have the exact URL, does NOT need a browser
   at all - a plain `curl` with no special headers downloaded it successfully. (An
   earlier attempt via a different automated fetcher was blocked by bot detection,
   which turned out to be specific to that fetcher's IP/fingerprint, not a general
   block on non-browser clients - worth knowing, since it means we don't need to
   route the actual (often large) file download through a heavier browser context.)

Folder ID (43866) and file ID (111510) stayed IDENTICAL between a Dec-2025 sample
and a Jul-2026 sample - this looks like a stable "slot" for this report series,
with only the filename-date and uuid changing per day's upload.

Usage:
    python scripts/fetch_ccil.py --out inbox/

Requires: playwright (pip install playwright && playwright install chromium), requests
"""
import argparse
import re
import sys
from pathlib import Path

import requests
from playwright.sync_api import sync_playwright

PAGE_URL = "https://www.ccilindia.com/daily-market-analysis"
# Matches the onclick="guestUserCheck('...pdf...download=true')" pattern
DOWNLOAD_RE = re.compile(r"guestUserCheck\('([^']+\.pdf[^']*)'\)")


def find_download_url() -> str | None:
    """Render the page with a real (headless) browser and pull today's link out
    of the DOM - a plain HTTP GET of this page does not include it."""
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page(
            user_agent=("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                        "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36")
        )
        page.goto(PAGE_URL, wait_until="networkidle", timeout=30000)
        page.wait_for_timeout(2000)  # give any trailing JS render pass a moment
        html = page.content()
        browser.close()

    m = DOWNLOAD_RE.search(html)
    return m.group(1) if m else None


def download_pdf(url: str, dest: Path):
    """Plain HTTP GET - confirmed sufficient (tested with curl, no special headers
    needed) once you have the exact, current URL. No browser required for this part."""
    resp = requests.get(url, timeout=30)
    resp.raise_for_status()
    dest.write_bytes(resp.content)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="directory to save the PDF into (e.g. inbox/)")
    args = ap.parse_args()

    out_dir = Path(args.out)
    out_dir.mkdir(parents=True, exist_ok=True)

    download_url = find_download_url()
    if not download_url:
        print("ERROR: could not find a guestUserCheck(...) download link on the rendered page. "
              "CCIL may have changed their page template - inspect manually (DevTools > "
              "rendered DOM, not view-source) and update DOWNLOAD_RE in this script.",
              file=sys.stderr)
        sys.exit(1)

    print(f"Found download URL: {download_url}")

    name_match = re.search(r"/([^/]+\.pdf)", download_url)
    filename = name_match.group(1) if name_match else "CCIL_DAILY_ANALYSIS.pdf"
    dest = out_dir / filename

    try:
        download_pdf(download_url, dest)
    except requests.RequestException as e:
        print(f"ERROR: plain HTTP download failed ({e}). This previously worked with a "
              f"plain curl request - if it's now blocked, it may be IP-reputation-based "
              f"(GitHub Actions runner IPs can differ from a home/office connection) rather "
              f"than anything about this script. Falling back would require routing the "
              f"download through the Playwright browser context instead (slower, but carries "
              f"a full browser fingerprint).", file=sys.stderr)
        sys.exit(1)

    print(f"Saved {dest}")


if __name__ == "__main__":
    main()

